[lint]
ignore = [
    "S112",
    "ASYNC230",
    "RUF012",
    "BLE001",
    "SIM102",
    "SIM113",
    "F841",
    "PLW1510",
    "ASYNC221",
    "TRY201",
    "TRY401",
    "F821",
    "PLW0602"
]
